<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'bz2tuleap\\converter' => '/Bz2Tuleap/Converter.php',
                'bz2tuleap\\tuleap\\artifact\\artifact' => '/Bz2Tuleap/Tuleap/Artifact/Artifact.php',
                'bz2tuleap\\tuleap\\artifact\\changeset\\ccfieldchange' => '/Bz2Tuleap/Tuleap/Artifact/Changeset/CCFieldChange.php',
                'bz2tuleap\\tuleap\\artifact\\changeset\\changeset' => '/Bz2Tuleap/Tuleap/Artifact/Changeset/Changeset.php',
                'bz2tuleap\\tuleap\\artifact\\changeset\\comment' => '/Bz2Tuleap/Tuleap/Artifact/Changeset/Comment.php',
                'bz2tuleap\\tuleap\\artifact\\changeset\\filefieldchange' => '/Bz2Tuleap/Tuleap/Artifact/Changeset/FileFieldChange.php',
                'bz2tuleap\\tuleap\\artifact\\changeset\\filesdata' => '/Bz2Tuleap/Tuleap/Artifact/Changeset/FilesData.php',
                'bz2tuleap\\tuleap\\artifact\\changeset\\listfieldchange' => '/Bz2Tuleap/Tuleap/Artifact/Changeset/ListFieldChange.php',
                'bz2tuleap\\tuleap\\artifact\\changeset\\scalarfieldchange' => '/Bz2Tuleap/Tuleap/Artifact/Changeset/ScalarFieldChange.php',
                'bz2tuleap\\tuleap\\artifact\\changeset\\usersselectboxfieldchange' => '/Bz2Tuleap/Tuleap/Artifact/Changeset/UsersSelectBoxFieldChange.php',
                'bz2tuleap\\tuleap\\field\\cc' => '/Bz2Tuleap/Tuleap/Field/CC.php',
                'bz2tuleap\\tuleap\\field\\column' => '/Bz2Tuleap/Tuleap/Field/Column.php',
                'bz2tuleap\\tuleap\\field\\defaultpermissions' => '/Bz2Tuleap/Tuleap/Field/DefaultPermissions.php',
                'bz2tuleap\\tuleap\\field\\field' => '/Bz2Tuleap/Tuleap/Field/Field.php',
                'bz2tuleap\\tuleap\\field\\fieldset' => '/Bz2Tuleap/Tuleap/Field/FieldSet.php',
                'bz2tuleap\\tuleap\\field\\formelements' => '/Bz2Tuleap/Tuleap/Field/FormElements.php',
                'bz2tuleap\\tuleap\\field\\idmapper' => '/Bz2Tuleap/Tuleap/Field/IdMapper.php',
                'bz2tuleap\\tuleap\\field\\ifield' => '/Bz2Tuleap/Tuleap/Field/IField.php',
                'bz2tuleap\\tuleap\\field\\iformelement' => '/Bz2Tuleap/Tuleap/Field/IFormElement.php',
                'bz2tuleap\\tuleap\\field\\ipermissions' => '/Bz2Tuleap/Tuleap/Field/IPermissions.php',
                'bz2tuleap\\tuleap\\field\\iproperties' => '/Bz2Tuleap/Tuleap/Field/IProperties.php',
                'bz2tuleap\\tuleap\\field\\nofieldpermissions' => '/Bz2Tuleap/Tuleap/Field/NoFieldPermissions.php',
                'bz2tuleap\\tuleap\\field\\noproperties' => '/Bz2Tuleap/Tuleap/Field/NoProperties.php',
                'bz2tuleap\\tuleap\\field\\properties' => '/Bz2Tuleap/Tuleap/Field/Properties.php',
                'bz2tuleap\\tuleap\\field\\readonlypermissions' => '/Bz2Tuleap/Tuleap/Field/ReadOnlyPermissions.php',
                'bz2tuleap\\tuleap\\field\\selectbox' => '/Bz2Tuleap/Tuleap/Field/SelectBox.php',
                'bz2tuleap\\tuleap\\field\\structure' => '/Bz2Tuleap/Tuleap/Field/Structure.php',
                'bz2tuleap\\tuleap\\field\\usersselectbox' => '/Bz2Tuleap/Tuleap/Field/UsersSelectBox.php',
                'bz2tuleap\\tuleap\\listrule' => '/Bz2Tuleap/Tuleap/ListRule.php',
                'bz2tuleap\\tuleap\\listrules' => '/Bz2Tuleap/Tuleap/ListRules.php',
                'bz2tuleap\\tuleap\\project' => '/Bz2Tuleap/Tuleap/Project.php',
                'bz2tuleap\\tuleap\\rules' => '/Bz2Tuleap/Tuleap/Rules.php',
                'bz2tuleap\\tuleap\\semantic\\assignedto' => '/Bz2Tuleap/Tuleap/Semantic/AssignedTo.php',
                'bz2tuleap\\tuleap\\semantic\\status' => '/Bz2Tuleap/Tuleap/Semantic/Status.php',
                'bz2tuleap\\tuleap\\semantic\\title' => '/Bz2Tuleap/Tuleap/Semantic/Title.php',
                'bz2tuleap\\tuleap\\tracker' => '/Bz2Tuleap/Tuleap/Tracker.php',
                'bz2tuleap\\tuleap\\trackerfactory' => '/Bz2Tuleap/Tuleap/TrackerFactory.php',
                'bz2tuleap\\tuleap\\usermapper' => '/Bz2Tuleap/Tuleap/UserMapper.php',
                'bz2tuleap\\xml\\cdata' => '/Bz2Tuleap/XML/CData.php',
                'bz2tuleap\\xml\\supportedencoding' => '/Bz2Tuleap/XML/SupportedEncoding.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    }
);
// @codeCoverageIgnoreEnd