name: Build and publish Docker images

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions: {}

env:
  IMAGE_NAME: enalean/bz2tuleap

jobs:
  build:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - name: Build image
        run: docker build -t ${{ env.IMAGE_NAME }} --label revision=${{ github.sha }} --label workflow_run_id=${{ github.run_id }} .
      - name: Install Cosign
        uses: sigstore/cosign-installer@dc72c7d5c4d10cd6bcb8cf6e3fd625a9e5e537da # tag=v3.7.0
      - name: Log into Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u bz2tuleappushbot --password-stdin
      - name: Publish image
        run: docker push ${{ env.IMAGE_NAME }}
      - name: Sign image
        run: |
          cosign sign --yes "$(docker inspect --format='{{index .RepoDigests 0}}' ${{ env.IMAGE_NAME }})"
